compressionLevel: 0

enableGlobalCache: false

enableTelemetry: false

enableTransparentWorkspaces: false

immutablePatterns:
  - .pnp.*

logFilters:
  - code: YN0005
    level: discard

pnpEnableEsmLoader: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
    - arm64-musl
  libc:
    - musl
  os:
    - linux
    - darwin

